
version: '3.8'
 
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # 生产环境应设为no并配置认证
#      - ZOO_ENABLE_AUTH=yes
#      - ZOO_SERVER_USERS=admin
#      - ZOO_SERVER_PASSWORDS=xxx
#      - ZOO_CLIENT_USER=admin2
#      - ZOO_CLIENT_PASSWORD=xxx
 
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
 #     - KAFKA_ZOOKEEPER_PROTOCOL=SASL
 #     - KAFKA_ZOOKEEPER_USER=admin
 #     - KAFKA_ZOOKEEPER_PASSWORD=xxx
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://9.134.240.223:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
